require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'gem_freshness_tasks.gemspec'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Layout/LineLength:
  Max: 110
